spring.application.name=observations

management.endpoint.shutdown.access=unrestricted
management.endpoints.web.exposure.include=*

management.endpoint.env.show-values=always

management.endpoint.health.show-details=always
management.endpoint.health.show-components=always
management.endpoint.health.group.readiness.include=ping,custom

management.info.env.enabled=true
info.app.encoding=UTF-8
info.app.java.source=26
info.app.java.target=26

management.tracing.sampling.probability=1.0